<?php

function  custom_api_menu(){  

   $items = array();

   $items['type/%/data'] = array (     
        'title' => 'News item list',
        'page callback' => 'custom_node_list',
        'page arguments'  => array(1),
        'access arguments' => array('access content'),
        'type' => MENU_CALLBACK
   );

   $items['type/%/data/%'] = array (     
        'title' => 'News item list',
        'page callback' => 'custom_node_retrieve',
        'page arguments'  => array(1,3),
        'access arguments' => array('access content'),
        'type' => MENU_CALLBACK
   ); 

 
   return $items;


}

function custom_node_list($content_type){

    $query = new EntityFieldQuery();

         $query
      ->entityCondition('entity_type', 'node', '=')
      ->propertyCondition('status', 1, '=')
      ->propertyCondition('type', $content_type, '=');
      $result = $query->execute();

    $nodes = node_load_multiple(array_keys($result['node']));

    foreach($nodes as $node){  
        // generate_styled_image_for_list()
        // generate_styled_image_for_retrieve()
      generate_styled_image($node, 'list');
      $output[] =$node;
    }

   backdrop_json_output($output);
   backdrop_exit();

}

function custom_node_retrieve($content_type,$nid){

    $query = new EntityFieldQuery();


          $query
      ->entityCondition('entity_type', 'node', '=')
      ->propertyCondition('status', 1, '=')
      ->propertyCondition('nid', $nid, '=')    
      ->propertyCondition('type', $content_type, '=');
      $result = $query->execute(); 


     $node = node_load(array_keys($result['node']));

     generate_styled_image($node, 'list');


   backdrop_json_output($node);
   backdrop_exit();

}

/*
* Generate styled image and URL for image fields using image_style
* @param $node - Which node to be used to generate image style
* @param $operation - node list or retrieve? 
*
*/

function generate_styled_image($node, $operation = Null){
   if($node->type == 'team'){
      $style_name = 'big_thumbnail';      
      if(!empty($node->field_profile_picture[und][0][uri])){
         $path = $node->field_profile_picture[und][0][uri]; 
         $style_url = image_style_url($style_name, $path);
         $node->field_profile_picture[und][0][uri] = $style_url;
      }
   }
   else if ($node->type == 'blog'){
         $style_name = 'big_thumbnail';      
         if(!empty($node->field_featured_image[und][0][uri])){
         $path = $node->field_featured_image[und][0][uri]; 
         $style_url = image_style_url($style_name, $path);
         $node->field_featured_image[und][0][uri] = $style_url;
      }
      
         $style_name = 'large';      
         if(!empty($node->field_header_image[und][0][uri])){
             $path = $node->field_header_image[und][0][uri]; 
             $style_url = image_style_url($style_name, $path);
             $node->field_header_image[und][0][uri] = $style_url;

      }
   
   }
   else if ($node->type == 'clients'){
         $style_name = 'big_thumbnail';      
         if(!empty($node->field_client_logo[und][0][uri])){
         $path = $node->field_client_logo[und][0][uri]; 
         $style_url = image_style_url($style_name, $path);
         $node->field_client_logo[und][0][uri] = $style_url;

      }
   }else if ($node->type == 'slider'){
         $style_name = 'large';      
         if(!empty($node->field_slider_image[und][0][uri])){
         $path = $node->field_slider_image[und][0][uri]; 
         $style_url = image_style_url($style_name, $path);
         $node->field_slider_image[und][0][uri] = $style_url;

      }
   }else if ($node->type == 'services'){
         $style_name = 'big_thumbnail';      
         if(!empty($node->field_service_image[und][0][uri])){
         $path = $node->field_service_image[und][0][uri]; 
         $style_url = image_style_url($style_name, $path);
         $node->field_service_image[und][0][uri] = $style_url;

      }
   }else if ($node->type == 'portfolio'){
         $style_name = 'medium';      
         if(!empty($node->field_portfolio_image[und][0][uri])){
         $path1 = $node->field_portfolio_image[und][0][uri]; 
         $style_url = image_style_url($style_name, $path1);
         $node->field_portfolio_image[und][0][uri] = $style_url;

      }

         $style_name = 'large';      
         if(empty($node->field_header_image[und][0][uri])){
         $style_url = image_style_url($style_name, $path1);
         $node->field_header_image[und][0][uri] = $style_url;

      }
   }

   

}

?>
